sudo: false

language: node_js

node_js:
  - 6
  - 8

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.email "kevin.brown@calligraphic.design"
  - git config --global user.name "Kevin Brown"

script:
  - npm run build
  - npm test

branches:
  only:
    - master
