branches:
  only:
  - master

environment:
  matrix:
  - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - git config --global user.email "kevin.brown@calligraphic.design"
  - git config --global user.name "Kevin Brown"
  - node --version
  - npm --version
  - npm run test:coverage

build: off
