// flow-typed signature: 7133fd6269793202396f15d802f3eb60
// flow-typed version: <<STUB>>/@sambego/storybook-state_v^1.0.6/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sambego/storybook-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sambego/storybook-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sambego/storybook-state/dist/index' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/dist/State' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/dist/Store' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/src/index' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/src/State' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/src/Store' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sambego/storybook-state/dist/index.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist/index'>;
}
declare module '@sambego/storybook-state/dist/State.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist/State'>;
}
declare module '@sambego/storybook-state/dist/Store.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist/Store'>;
}
declare module '@sambego/storybook-state/src/index.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/src/index'>;
}
declare module '@sambego/storybook-state/src/State.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/src/State'>;
}
declare module '@sambego/storybook-state/src/Store.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/src/Store'>;
}
