// flow-typed signature: b34ee3fe213d51c05e16ed44faf524aa
// flow-typed version: <<STUB>>/react-storybook-addon-chapters_v^2.1.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-storybook-addon-chapters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-storybook-addon-chapters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-storybook-addon-chapters/dist/components/Chapter' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/dist/components/PropTable' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/dist/components/Section' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/dist/components/Story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/dist/index' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/dist/theme' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/dist/utils/info-content' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/example/Button' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/example/my-story/story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/example/story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/components/Chapter' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/components/PropTable' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/components/Section' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/components/Story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/index' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/tests/index' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/theme' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-chapters/src/utils/info-content' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-storybook-addon-chapters/dist/components/Chapter.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/dist/components/Chapter'>;
}
declare module 'react-storybook-addon-chapters/dist/components/PropTable.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/dist/components/PropTable'>;
}
declare module 'react-storybook-addon-chapters/dist/components/Section.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/dist/components/Section'>;
}
declare module 'react-storybook-addon-chapters/dist/components/Story.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/dist/components/Story'>;
}
declare module 'react-storybook-addon-chapters/dist/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/dist/index'>;
}
declare module 'react-storybook-addon-chapters/dist/theme.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/dist/theme'>;
}
declare module 'react-storybook-addon-chapters/dist/utils/info-content.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/dist/utils/info-content'>;
}
declare module 'react-storybook-addon-chapters/example/Button.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/example/Button'>;
}
declare module 'react-storybook-addon-chapters/example/my-story/story.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/example/my-story/story'>;
}
declare module 'react-storybook-addon-chapters/example/story.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/example/story'>;
}
declare module 'react-storybook-addon-chapters/src/components/Chapter.jsx' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/components/Chapter'>;
}
declare module 'react-storybook-addon-chapters/src/components/PropTable.jsx' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/components/PropTable'>;
}
declare module 'react-storybook-addon-chapters/src/components/Section.jsx' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/components/Section'>;
}
declare module 'react-storybook-addon-chapters/src/components/Story.jsx' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/components/Story'>;
}
declare module 'react-storybook-addon-chapters/src/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/index'>;
}
declare module 'react-storybook-addon-chapters/src/tests/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/tests/index'>;
}
declare module 'react-storybook-addon-chapters/src/theme.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/theme'>;
}
declare module 'react-storybook-addon-chapters/src/utils/info-content.js' {
  declare module.exports: $Exports<'react-storybook-addon-chapters/src/utils/info-content'>;
}
