// flow-typed signature: 6128b5b44feb27a3828a42f466379661
// flow-typed version: <<STUB>>/redux-orm-proptypes_vgithub:calligraphic/redux-orm-proptypes/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-orm-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-orm-proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-orm-proptypes/lib/index' {
  declare module.exports: any;
}

declare module 'redux-orm-proptypes/lib/index.test' {
  declare module.exports: any;
}

declare module 'redux-orm-proptypes/src/index' {
  declare module.exports: any;
}

declare module 'redux-orm-proptypes/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-orm-proptypes/lib/index.js' {
  declare module.exports: $Exports<'redux-orm-proptypes/lib/index'>;
}
declare module 'redux-orm-proptypes/lib/index.test.js' {
  declare module.exports: $Exports<'redux-orm-proptypes/lib/index.test'>;
}
declare module 'redux-orm-proptypes/src/index.js' {
  declare module.exports: $Exports<'redux-orm-proptypes/src/index'>;
}
declare module 'redux-orm-proptypes/src/index.test.js' {
  declare module.exports: $Exports<'redux-orm-proptypes/src/index.test'>;
}
