// flow-typed signature: d938ab18fe2a123c92fc39cbdf6319a0
// flow-typed version: <<STUB>>/redux-orm_v^0.9.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-orm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-orm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-orm/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-orm/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-orm/dist/redux-orm' {
  declare module.exports: any;
}

declare module 'redux-orm/dist/redux-orm.min' {
  declare module.exports: any;
}

declare module 'redux-orm/gulpfile' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/db/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/db/index' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/db/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/descriptors' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/index' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/memoize' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testDatabase' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testIntegrations' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testModel' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testORM' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testQuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testReduxIntegration' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testSession' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testTable' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/testUtils' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/test/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/src/constants' {
  declare module.exports: any;
}

declare module 'redux-orm/src/db/Database' {
  declare module.exports: any;
}

declare module 'redux-orm/src/db/index' {
  declare module.exports: any;
}

declare module 'redux-orm/src/db/Table' {
  declare module.exports: any;
}

declare module 'redux-orm/src/descriptors' {
  declare module.exports: any;
}

declare module 'redux-orm/src/fields' {
  declare module.exports: any;
}

declare module 'redux-orm/src/index' {
  declare module.exports: any;
}

declare module 'redux-orm/src/memoize' {
  declare module.exports: any;
}

declare module 'redux-orm/src/Model' {
  declare module.exports: any;
}

declare module 'redux-orm/src/ORM' {
  declare module.exports: any;
}

declare module 'redux-orm/src/QuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/src/redux' {
  declare module.exports: any;
}

declare module 'redux-orm/src/Session' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testDatabase' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testIntegrations' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testModel' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testORM' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testQuerySet' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testReduxIntegration' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testSession' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testTable' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/testUtils' {
  declare module.exports: any;
}

declare module 'redux-orm/src/test/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/src/utils' {
  declare module.exports: any;
}

declare module 'redux-orm/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-orm/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-orm/coverage/lcov-report/prettify'>;
}
declare module 'redux-orm/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-orm/coverage/lcov-report/sorter'>;
}
declare module 'redux-orm/dist/redux-orm.js' {
  declare module.exports: $Exports<'redux-orm/dist/redux-orm'>;
}
declare module 'redux-orm/dist/redux-orm.min.js' {
  declare module.exports: $Exports<'redux-orm/dist/redux-orm.min'>;
}
declare module 'redux-orm/gulpfile.js' {
  declare module.exports: $Exports<'redux-orm/gulpfile'>;
}
declare module 'redux-orm/lib/constants.js' {
  declare module.exports: $Exports<'redux-orm/lib/constants'>;
}
declare module 'redux-orm/lib/db/Database.js' {
  declare module.exports: $Exports<'redux-orm/lib/db/Database'>;
}
declare module 'redux-orm/lib/db/index.js' {
  declare module.exports: $Exports<'redux-orm/lib/db/index'>;
}
declare module 'redux-orm/lib/db/Table.js' {
  declare module.exports: $Exports<'redux-orm/lib/db/Table'>;
}
declare module 'redux-orm/lib/descriptors.js' {
  declare module.exports: $Exports<'redux-orm/lib/descriptors'>;
}
declare module 'redux-orm/lib/fields.js' {
  declare module.exports: $Exports<'redux-orm/lib/fields'>;
}
declare module 'redux-orm/lib/index.js' {
  declare module.exports: $Exports<'redux-orm/lib/index'>;
}
declare module 'redux-orm/lib/memoize.js' {
  declare module.exports: $Exports<'redux-orm/lib/memoize'>;
}
declare module 'redux-orm/lib/Model.js' {
  declare module.exports: $Exports<'redux-orm/lib/Model'>;
}
declare module 'redux-orm/lib/ORM.js' {
  declare module.exports: $Exports<'redux-orm/lib/ORM'>;
}
declare module 'redux-orm/lib/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/lib/QuerySet'>;
}
declare module 'redux-orm/lib/redux.js' {
  declare module.exports: $Exports<'redux-orm/lib/redux'>;
}
declare module 'redux-orm/lib/Session.js' {
  declare module.exports: $Exports<'redux-orm/lib/Session'>;
}
declare module 'redux-orm/lib/test/testDatabase.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testDatabase'>;
}
declare module 'redux-orm/lib/test/testIntegrations.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testIntegrations'>;
}
declare module 'redux-orm/lib/test/testModel.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testModel'>;
}
declare module 'redux-orm/lib/test/testORM.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testORM'>;
}
declare module 'redux-orm/lib/test/testQuerySet.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testQuerySet'>;
}
declare module 'redux-orm/lib/test/testReduxIntegration.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testReduxIntegration'>;
}
declare module 'redux-orm/lib/test/testSession.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testSession'>;
}
declare module 'redux-orm/lib/test/testTable.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testTable'>;
}
declare module 'redux-orm/lib/test/testUtils.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/testUtils'>;
}
declare module 'redux-orm/lib/test/utils.js' {
  declare module.exports: $Exports<'redux-orm/lib/test/utils'>;
}
declare module 'redux-orm/lib/utils.js' {
  declare module.exports: $Exports<'redux-orm/lib/utils'>;
}
declare module 'redux-orm/src/constants.js' {
  declare module.exports: $Exports<'redux-orm/src/constants'>;
}
declare module 'redux-orm/src/db/Database.js' {
  declare module.exports: $Exports<'redux-orm/src/db/Database'>;
}
declare module 'redux-orm/src/db/index.js' {
  declare module.exports: $Exports<'redux-orm/src/db/index'>;
}
declare module 'redux-orm/src/db/Table.js' {
  declare module.exports: $Exports<'redux-orm/src/db/Table'>;
}
declare module 'redux-orm/src/descriptors.js' {
  declare module.exports: $Exports<'redux-orm/src/descriptors'>;
}
declare module 'redux-orm/src/fields.js' {
  declare module.exports: $Exports<'redux-orm/src/fields'>;
}
declare module 'redux-orm/src/index.js' {
  declare module.exports: $Exports<'redux-orm/src/index'>;
}
declare module 'redux-orm/src/memoize.js' {
  declare module.exports: $Exports<'redux-orm/src/memoize'>;
}
declare module 'redux-orm/src/Model.js' {
  declare module.exports: $Exports<'redux-orm/src/Model'>;
}
declare module 'redux-orm/src/ORM.js' {
  declare module.exports: $Exports<'redux-orm/src/ORM'>;
}
declare module 'redux-orm/src/QuerySet.js' {
  declare module.exports: $Exports<'redux-orm/src/QuerySet'>;
}
declare module 'redux-orm/src/redux.js' {
  declare module.exports: $Exports<'redux-orm/src/redux'>;
}
declare module 'redux-orm/src/Session.js' {
  declare module.exports: $Exports<'redux-orm/src/Session'>;
}
declare module 'redux-orm/src/test/testDatabase.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testDatabase'>;
}
declare module 'redux-orm/src/test/testIntegrations.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testIntegrations'>;
}
declare module 'redux-orm/src/test/testModel.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testModel'>;
}
declare module 'redux-orm/src/test/testORM.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testORM'>;
}
declare module 'redux-orm/src/test/testQuerySet.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testQuerySet'>;
}
declare module 'redux-orm/src/test/testReduxIntegration.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testReduxIntegration'>;
}
declare module 'redux-orm/src/test/testSession.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testSession'>;
}
declare module 'redux-orm/src/test/testTable.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testTable'>;
}
declare module 'redux-orm/src/test/testUtils.js' {
  declare module.exports: $Exports<'redux-orm/src/test/testUtils'>;
}
declare module 'redux-orm/src/test/utils.js' {
  declare module.exports: $Exports<'redux-orm/src/test/utils'>;
}
declare module 'redux-orm/src/utils.js' {
  declare module.exports: $Exports<'redux-orm/src/utils'>;
}
declare module 'redux-orm/webpack.config.js' {
  declare module.exports: $Exports<'redux-orm/webpack.config'>;
}
